[build]
  command = "yarn build"

[dev]
  autoLaunch = false
  command = "vite dev"
  targetPort = 3000
  port = 8080

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  force = true
  from = '/api/*'
  status = 200
  to = '/.netlify/functions/:splat'